import Head from 'next/head';
import Layout from '@/components/Layout';

export default function About() {
    return (
        <>
            <Head>
                <title>Blitz - Contact</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <section style={{minHeight: '80vh', backgroundColor: '#000', display: 'grid', placeItems: "center"}}>
                    Contact
                </section>
            </Layout>
        </>
    );
}
